run:
  deadline: 10m
linters-settings:
  gocyclo:
    min-complexity: 30
  lll:
    line-length: 180
  gci:
    sections:
      - standard
      - default
      - blank
      - dot
    skip-generated: false
    custom-order: true
  goconst:
    ignore-strings: "true|false"
  errcheck:
    check-type-assertions: true
  exhaustive:
    check:
      - switch
    default-signifies-exhaustive: true
  funlen:
    lines: 100
    statements: 100
    ignore-comments: true
  nolintlint:
    allow-no-explanation: [funlen, lll]
    require-specific: true
  ireturn:
    allow:
      # defaults https://golangci-lint.run/usage/linters/#ireturn
      - anon
      - error
      - empty
      - stdlib
  revive:
    rules:
      - name: dot-imports
        arguments:
          - allowedPackages: ["github.com/onsi/ginkgo/v2", "github.com/onsi/gomega", "github.com/onsi/gomega/gstruct"]
  perfsprint:
    sprintf1: false
    strconcat: false
  # Enable gocritic for detecting bugs, performance, and style issues: https://golangci-lint.run/usage/linters/#gocritic
  gocritic:
    # https://go-critic.com/overview.html#checkers
    enabled-checks:
      - deferInLoop
      - unnecessaryDefer
linters:
  disable-all: true
  enable:
    - gci
issues:
  exclude-dirs:
    - apis
