apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-server-cert
spec:
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
    name: webhook
  selector:
    app.kubernetes.io/name: llama-stack-k8s-operator
    app.kubernetes.io/component: controller-manager 